CRM/CRM/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('first.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls'))
]

CRM/apps/first/urls.py
from django.urls import path
from . import views
from django.urls import re_path

urlpatterns = [
    path('', views.Base.as_view(), name='BaseView'),

    path('Record/', views.RecordListView.as_view(), name='RecordListView'),
    path('Record/<int:pk>/', views.RecordDetailView.as_view(), name='RecordDetailView'),
    path('Project', views.ProjectListView.as_view(), name='ProjectListView'),
    path('Interaction', views.InteractionFilterView.as_view(), name='InteractionFilterView'),
    path('Interaction/<int:pk>/', views.InteractionDetailView.as_view(), name='InteractionDetailView'),

    path('Create/CompanyAddress/', views.CompanyAddressCreate.as_view(), name='CompanyAddressCreate'),
    path('Create/Descriptin/', views.DescriptinCreate.as_view(), name='DescriptinCreate'),
    path('Create/Record/', views.RecordCreate.as_view(), name='RecordCreate'),
    path('Create/Project/', views.ProjectCreate.as_view(), name='ProjectCreate'),
    path('Create/Communication/', views.CommunicationCreate.as_view(), name='CommunicationCreate'),
    path('Create/Interaction/', views.InteractionCreate.as_view(), name='InteractionCreate'),
]

CRM/apps/first/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class CompanyAddress(models.Model):
    address = models.CharField('Адрес', max_length=255)
    phone_number = models.CharField('Номер телефона', max_length=100)
    e_mail = models.EmailField('E-mail', primary_key=True)

    class Meta:
        verbose_name = 'Адрес'
        verbose_name_plural = 'Адреса'

    def __str__(self):
        return f'{self.phone_number}|{self.e_mail}'

class Descriptin(models.Model):
    description = models.TextField('Описание')

    def __str__(self):
        return self.description

class Record(models.Model):
    name_company = models.CharField('Название компании', max_length=100)
    name_manager = models.CharField('ФИО руководителя', max_length=100)
    description_id = models.OneToOneField(Descriptin, on_delete=models.CASCADE)
    crt_date = models.DateField('Дата создание', auto_now_add=True, editable=False)
    date_record = models.DateField('Дата изменения записи', auto_now=True, editable=False)
    address = models.OneToOneField(CompanyAddress, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'

    def __str__(self):
        return f'{self.pk} {self.name_company}'

class Project(models.Model):
    name_project = models.CharField('Название проекта', max_length=255)
    description_id = models.OneToOneField(Descriptin, on_delete=models.CASCADE)
    start_date = models.DateField('Сроки начала')
    deadline = models.DateField('Срок окончания')
    cost = models.FloatField('Стоимость')
    status = models.BooleanField('Статус')

    class Meta:
        verbose_name = 'Проект'
        verbose_name_plural = 'Проекты'

    def __str__(self):
        return f'{self.pk} {self.name_project}'

class Communication(models.Model):
    communication = models.CharField('Канала обращения', max_length=25)

    def __str__(self):
        return self.communication

class Interaction(models.Model):
    project_id = models.ForeignKey(Project, on_delete=models.CASCADE)
    company_id = models.ForeignKey(Record, on_delete=models.CASCADE)
    communication_id = models.ForeignKey(Communication, on_delete=models.DO_NOTHING)
    name_manager = models.CharField('Имя менеджера', max_length=255, null=True)
    description_id = models.OneToOneField(Descriptin, on_delete=models.CASCADE, blank=True)
    appraisal = models.PositiveSmallIntegerField('Оценка', default=0)  # оценки от 0 до 10

    class Meta:
        verbose_name = 'Взаимодействия'
        verbose_name_plural = 'Взаимодействия'

    def __str__(self):
        return f'{self.pk}  "{self.project_id} | {self.company_id}"'

CRM/apps/first/forms.py
from django.core.exceptions import ValidationError

from django import forms

# from .models import Record, Project, Interaction
from .models import CompanyAddress, Descriptin, Record, Project, \
    Communication, Interaction


class CompanyAddressForm(forms.ModelForm):
    class Meta:
        model = CompanyAddress
        fields = ('address', 'phone_number', 'e_mail')
        widgets = {
            'address': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите адрес'
            }),
            'phone_number': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите телефон format "097 1593 367"',
                'type': 'tel',
                'pattern': "[0-9]{3} [0-9]{4} [0-9]{3}"
            }),
            'e_mail': forms.EmailInput(attrs={

                'class': 'form-control',
                'placeholder': 'Введите e-mail'
            })
        }


class DescriptinForm(forms.ModelForm):
    class Meta:
        model = Descriptin
        fields = ('description', )
        widgets = {
            'description': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Введите Описание'
            })
        }


class RecordForm(forms.ModelForm):
    class Meta:
        model = Record
        fields = ('name_company', 'name_manager', 'description_id', 'address')
        widgets = {
            'description_id': forms.Select(attrs={
                'id': 'description_id',
                'name': 'description_id',
                'class': 'form-control m-2'
            }),
            'address': forms.Select(attrs={
                'id': 'address_id',
                'name': 'address_id',
                'class': 'form-control m-2',
            }),
            'name_company': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите название компании'
            }),
            'name_manager': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите ФИО руководителя'
            })
        }


class ProjectForm(forms.ModelForm):
    CHOICES = [('1', 'True'), ('2', 'False')]
    status = forms.ChoiceField(widget=forms.RadioSelect, choices=CHOICES)

    class Meta:
        model = Project
        fields = ('name_project', 'description_id', 'start_date', 'deadline', 'cost', 'status')
        widgets = {
            'name_project': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите название компании'
            }),
            'description_id': forms.Select(attrs={
                'id': 'description_id',
                'name': 'description_id',
                'class': 'form-control m-2'
            }),
            'start_date': forms.DateInput(attrs={
                'class': 'form-control',
                'type': 'date',
            }),
            'deadline': forms.DateInput(attrs={
                'class': 'form-control',
                'type': 'date',
            }),
            'cost': forms.NumberInput(attrs={
                'class': 'form-control',
                'min': '1',
                'step': 'any',
                'placeholder': 'Введите стоймость проекта Format: 1 < n'
            }),
            'status': forms.RadioSelect(attrs={
                'class': 'form-control',
                'type': 'radio'
            })
        }


class CommunicationForm(forms.ModelForm):
    class Meta:
        model = Communication
        fields = ('__all__' )
        widgets = {
            'communication': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите взаимодействия'
            })
        }

class InteractionForm(forms.ModelForm):
    appraisal = forms.IntegerField(min_value=0, max_value=10)  # оценки от 0 до 10
    class Meta:
        model = Interaction
        fields = ('project_id', 'company_id', 'communication_id', 'name_manager', 'description_id', 'appraisal')
        widgets = {
            'project_id': forms.Select(attrs={
                'id': 'project_id',
                'name': 'project_id',
                'class': 'form-control m-2'
            }),
            'company_id': forms.Select(attrs={
                'id': 'company_id',
                'name': 'company_id',
                'class': 'form-control m-2'
            }),
            'communication_id': forms.Select(attrs={
                'id': 'communication_id',
                'name': 'communication_id',
                'class': 'form-control m-2'
            }),
            'name_manager': forms.TextInput(attrs={
                'class': 'form-control mt-3',
                'placeholder': 'Введите ФИО менеджера'
            }),
            'description_id': forms.Select(attrs={
                'id': 'description_id',
                'name': 'description_id',
                'class': 'form-control m-2'
            })
        }

# 'appraisal': forms.NumberInput(attrs={
#                 'class': 'form-control m-2',
#                 'type': 'number',
#                 'min': '1',
#                 'max': '10',
#                 'placeholder': 'Введите оценку'
#             })
# class DogRequestForm(f eld(queryset=Speed.objects.all())
        # labels = {}

CRM/apps/first/views.py
from django.shortcuts import render, redirect
# Create your views here.
from . import models # Record, Project, Interaction, Communication
from django.views.generic import View, DetailView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin


class Base(View):  # Для вывода базового Base.html
    template_name = r'first\Base.html'

    def get(self, request):
        return render(request, self.template_name)

# _____________________________________| List View |_____________________________________


class RecordListView(ListView):
    # login_url = '/accounts/login/'
    model = models.Record
    paginate_by = 5
    template_name = r'first\RecordList.html'
    context_object_name = 'id'
    queryset = model.objects.all()

    def get_ordering(self):
        ordering = self.request.GET.get('ordering')
        return ordering


class ProjectListView(ListView):
    model = models.Project
    paginate_by = 5
    template_name = r'first\ProjectList.html'
    queryset = model.objects.all()
    context_object_name = 'projects'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['count'] = self.queryset.count()
        context['count_all'] = self.model.objects.count()
        return context

    def get_queryset(self):
        filter_val = self.request.GET.get('status')
        if filter_val != '' and filter_val is not None:
            self.queryset = self.queryset.filter(status=filter_val,)
        return self.queryset


class InteractionFilterView(ListView):  # List
    model = models.Interaction
    paginate_by = 5
    # template_name = r'first\InteractionList.html'
    template_name = r'first\InteractionFilter.html'
    queryset = model.objects.all()
    context_object_name = 'interactions'

    @staticmethod
    def is_valid_context(filter_val):
        return filter_val != '' and filter_val is not None

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['projects'] = models.Project.objects.distinct()
        context['records'] = models.Record.objects.distinct()
        context['communications'] = models.Communication.objects.distinct()
        return context

    def get_queryset(self):
        filter_project = self.request.GET.get('project')
        filter_record = self.request.GET.get('record')
        filter_communication = self.request.GET.get('communication')
        new_context = self.queryset

        if self.is_valid_context(filter_project):
            new_context = new_context.filter(project_id=filter_project, )
        if self.is_valid_context(filter_record):
            new_context = new_context.filter(company_id=filter_record, )
        if self.is_valid_context(filter_communication):
            new_context = new_context.filter(communication_id=filter_communication, )

        return new_context
# _____________________________________| NEXT Detail View |_____________________________________


class RecordDetailView(DetailView):
    model = models.Record
    template_name = r'first\RecordDetal.html'

    def get(self, pk, *args, **kwargs):
        content = {'record': self.model.objects.get(id=pk)}
        return render(self.request, self.template_name, content)


class InteractionDetailView(DetailView):  # Detail
    model = models.Interaction
    template_name = r'first\InteractionDetai.html'

    def get(self, pk, *args, **kwargs):
        content = {'interaction': self.model.objects.get(id=pk)}
        return render(self.request, self.template_name, content)
# _____________________________________| NEXT Forms |_____________________________________


from .forms import CompanyAddressForm, DescriptinForm, RecordForm,\
    ProjectForm, CommunicationForm, InteractionForm


class CompanyAddressCreate(LoginRequiredMixin, View):
    form_class = CompanyAddressForm
    initial = {'key': 'value'}
    template_name = r'first\Create\CompanyAddressCreate.html'

    def get(self, request):
        form = self.form_class(self.initial)
        context = {
            'form': form,
        }
        return render(request, self.template_name, context)

    def post(self, request):
        error = ''
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            return redirect('BaseView')
        else:
            error = 'Форма была Неверной'
        context = {
            'form': form,
            'error': error
        }
        return render(request, self.template_name, context)


class DescriptinCreate(LoginRequiredMixin, View):
    form_class = DescriptinForm
    initial = {'key': 'value'}
    template_name = r'first\Create\DescriptinCreate.html'

    def get(self, request):
        form = self.form_class(self.initial)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            return redirect('BaseView')

        return render(request, self.template_name, {'form': form})


class RecordCreate(LoginRequiredMixin, View):
    form_class = RecordForm
    initial = {'key': 'value'}
    template_name = r'first\Create\RecordCreate.html'

    def get(self, request):
        form = self.form_class(self.initial)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            return redirect('RecordListView')

        return render(request, self.template_name, {'form': form})


class ProjectCreate(LoginRequiredMixin, View):
    form_class = ProjectForm
    initial = {'key': 'value'}
    template_name = r'first\Create\ProjectCreate.html'

    def get(self, request):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            return redirect('BaseView')

        return render(request, self.template_name, {'form': form})


class CommunicationCreate(LoginRequiredMixin, View):
    form_class = CommunicationForm
    initial = {'key': 'value'}
    template_name = r'first\Create\CommunicationCreate.html'

    def get(self, request):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            return redirect('BaseView')

        return render(request, self.template_name, {'form': form})


class InteractionCreate(LoginRequiredMixin, View):
    form_class = InteractionForm
    initial = {'key': 'value'}
    template_name = r'first\Create\InteractionCreate.html'

    def get(self, request):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            return redirect('BaseView')

        return render(request, self.template_name, {'form': form})
# _____________________________________| END |_____________________________________

CRM/templates/first/Create/CommunicationCreate.html
{% extends 'first/base.html' %}

{% block title %}
New post
{% endblock title %}

{% block content %}
<div class="starter-template">
    <h3>New communication</h3>
    <form method="post"  class="form-control mr-sm-2">
        {% csrf_token %}
        {{ form.communication }} <br>
        <button type="submit" class="btn btn-primary btn-lg m-3">Save</button>
    </form>
</div>


{% endblock content %}

CRM/templates/first/Create/CompanyAddressCreate.html
{% extends 'first/base.html' %}

{% block title %}
New post
{% endblock title %}

{% block content %}
<div class="starter-template">
    <h3>New CompanyAddress</h3>
    <form method="post"  class="form-control mr-sm-2">
        {% csrf_token %}
        {{ form.address }} <br>
        {{ form.phone_number }} <br>
        {{ form.e_mail }} <br>
        <button type="submit" class="btn btn-primary btn-lg m-3">Save</button>
    </form>
</div>


{% endblock content %}

CRM/templates/first/Create/DescriptinCreate.html
{% extends 'first/base.html' %}

{% block title %}
New post
{% endblock title %}

{% block content %}
<div class="starter-template">
    <h3>New Description</h3>
    <form method="post"  class="form-control mr-sm-2">
        {% csrf_token %}
        {{ form.description }} <br>
        <button type="submit" class="btn btn-primary btn-lg m-3">Save</button>
    </form>
</div>


{% endblock content %}

CRM/templates/first/Create/InteractionCreate.html
{% extends 'first/base.html' %}

{% block title %}
 InteractionCreate
{% endblock title %}

{% block content %}
<div class="starter-template">
    <h3>InteractionCreate</h3>
    <form method="post"  class="form-control mr-sm-2">
        {% csrf_token %}

        <label class="m-2" for="project_id">project_id</label>
        {{ form.project_id }}
        <button type="button" class="btn btn-warning">
            <a target="popup" onclick="window.open('{% url 'DescriptinCreate' %}','DescriptinCreate','width=600,height=400')" >
                Create new Description
            </a>
        </button> <br>

        <label class="m-2" for="company_id">company_id</label>
        {{ form.company_id }}
        <button type="button" class="btn btn-warning">
            <a target="popup" onclick="window.open('{% url 'DescriptinCreate' %}','DescriptinCreate','width=600,height=400')" >
                Create new Description
            </a>
        </button> <br>

        <label class="m-2" for="communication_id">communication_id</label>
        {{ form.communication_id }}
        <button type="button" class="btn btn-warning">
            <a target="popup" onclick="window.open('{% url 'DescriptinCreate' %}','DescriptinCreate','width=600,height=400')" >
                Create new Description
            </a>
        </button> <br>
        {{ form.name_manager }}<br>

        <label class="m-2" for="description_id">description_id</label>
        {{ form.description_id }}
        <button type="button" class="btn btn-warning">
            <a target="popup"
               onclick="window.open('{% url 'DescriptinCreate' %}','DescriptinCreate','width=600,height=400')" >
                Create new Description
            </a>
        </button> <br>
            <input placeholder="Введите оценку: 1 &le; n &le; 10" class="form-control mt-3" type="number" name="appraisal" min="0" max="10" required="" id="id_appraisal">
        <br>
        <button type="submit" class="btn btn-primary btn-lg m-3">Save</button>
    </form>
<!--    <p class="lead">-->
<!--        <b>Название проекта</b> = "" <br>-->
<!--        <b>Название компании</b> = <br>-->
<!--        <b>Канала обращения</b> =  <br>-->
<!--        <b>Who</b> =  <br>-->
<!--        <b>Описание</b> =  <br>-->
<!--        <b>Оценка</b> =  <br>-->
<!--    </p>-->
</div>
{% endblock content %}

CRM/templates/first/Create/ProjectCreate.html
{% extends 'first/base.html' %}

{% block title %}
ProjectCreate
{% endblock title %}

{% block content %}
<div class="starter-template">
    <h3>ProjectCreate</h3>
    <form method="post"  class="form-control mr-sm-2">
        {% csrf_token %}
        {{ form.name_project }}<br>
        <label class="m-2" for="description_id">description_id</label>
        {{ form.description_id }}
        <button type="button" class="btn btn-warning">
            <a target="popup" onclick="window.open('{% url 'DescriptinCreate' %}','DescriptinCreate','width=600,height=400')" >
                Create new Description
            </a>
        </button>
        <br>
        {{ form.start_date }}<br>
        {{ form.deadline }}<br>
        {{ form.cost }}<br>
        {{ form.status }}<br>
        <button type="submit" class="btn btn-primary btn-lg m-3">Save</button>

    </form>
</div>
{% endblock content %}

CRM/templates/first/Create/RecordCreate.html
{% extends 'first/base.html' %}

{% block title %}
 RecordCreate
{% endblock title %}

{% block content %}
<div class="starter-template">
    <h3>RecordCreate</h3>
    <form method="post"  class="form-control mr-sm-2">
        {% csrf_token %}
        {{ form.name_company}}<br>
        {{ form.name_manager}}<br>
        <label class="m-2" for="description_id">description_id</label>
        {{ form.description_id}}
        <button type="button" class="btn btn-warning">
            <a target="popup" onclick="window.open('{% url 'DescriptinCreate' %}','DescriptinCreate','width=600,height=400')" >
                Create new Description
            </a>
        </button>
        <br>
        <label class="m-2" for="address_id">address_id</label>
        {{ form.address}}
        <button type="button" class=" btn btn-warning">
            <a target="popup" onclick="window.open('{% url 'CompanyAddressCreate' %}','CompanyAddressCreate','width=600,height=400')" >
                Create new Address
            </a>
        </button> <br>
        <button type="submit" class="btn btn-primary btn-lg m-3">Save</button>
    </form>
</div>


{% endblock content %}